trigger:
  branches:
    include:
      - main

pool:
  name: 'Azure Pipelines'  # Use the self-hosted agent pool 

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    projects: '**/*.csproj'
    versioningScheme: 'off'  # Disable versioning

- task: NuGetCommand@2
  inputs:
    command: 'push'
    publishVstsFeed: 'your-feed-id'  # Azure Artifacts feed
    packagesToPush: '**/*.nupkg'
